'use client';

export function Disclaimer() {
    return (
        <footer className="mt-16 pt-8 border-t border-rule">
            <p className="text-micro text-ink-3 max-w-3xl leading-relaxed">
                StockSage AI is a research preview, not investment advice. We are not a SEBI-Registered
                Investment Advisor. The verdict is generated by language models reasoning over public
                fundamental, technical, and news data; stop losses and position sizes are computed from
                heuristic models and may differ materially from actual outcomes. No price target is
                shown, because the models behind it do not currently agree closely enough to state one. Past performance does
                not guarantee future returns. Consult a SEBI RIA before acting on any output.
            </p>
        </footer>
    );
}
