'use client';

export function Disclaimer() {
    return (
        <footer className="mt-16 pt-8 border-t border-[#E5E3DB]">
            <p className="text-micro text-[#7A7F88] max-w-3xl leading-relaxed">
                StockSage AI is a research preview, not investment advice. We are not a SEBI-Registered
                Investment Advisor. The verdict is generated by language models reasoning over public
                fundamental, technical, and news data; price targets and stop losses are computed from
                heuristic models and may differ materially from actual outcomes. Past performance does
                not guarantee future returns. Consult a SEBI RIA before acting on any output.
            </p>
        </footer>
    );
}
